### ISSUE TITLE
security: Ensure requests to the tool come only from the Wikimedia domains

### ISSUE THREAD

**Issue by Alwoch** [WikiMovimentoBrasil/deadlinkchecker#27]

**Comment by albertoleoncio** [comment]
* Load script here in order to get window.opener.location.host
    * Send back to server: wiki adress + session_id: https://deadlinkchecker.toolforge.org/finishlogin?wiki={wiki_address}&sessionid={session_id}
    * Saves on database: UPDATE users SET language = $wiki WHERE session_id = $session_id
    * Redirects user to Special:Deadlinkchecker
